services:
  web:
    build: .
    container_name: django_app

    # command: "gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000"

    # volumes:
    #   - .:/portfolio

    ports:
      - "8000:8000"

    environment:
      - DJANGO_DEBUG=False

    networks:
      - proxy

networks:
  proxy:
    external: true